var T,baidu=T=baidu||{version:"1.3.4"};baidu.guid="$BAIDU$";window[baidu.guid]=window[baidu.guid]||{};baidu.page=baidu.page||{};baidu.page.getScrollTop=function(){var a=document;return window.pageYOffset||a.documentElement.scrollTop||a.body.scrollTop};baidu.page.getViewHeight=function(){var a=document;return(a.compatMode=="BackCompat"?a.body:a.documentElement).clientHeight};baidu.dom=baidu.dom||{};
baidu.dom.g=function(a){if("string"==typeof a||a instanceof String)return document.getElementById(a);else if(a&&a.nodeName&&(a.nodeType==1||a.nodeType==9))return a;return null};baidu.g=baidu.G=baidu.dom.g;baidu.dom.getDocument=function(a){a=baidu.dom.g(a);return a.nodeType==9?a:a.ownerDocument||a.document};baidu.dom._styleFixer=baidu.dom._styleFixer||{};baidu.dom._styleFilter=baidu.dom._styleFilter||[];
baidu.dom._styleFilter.filter=function(a,b,f){for(var e=0,d=baidu.dom._styleFilter,c;c=d[e];e++)if(c=c[f])b=c(a,b);return b};baidu.string=baidu.string||{};baidu.string.toCamelCase=function(a){if(a.indexOf("-")<0&&a.indexOf("_")<0)return a;return a.replace(/[-_][^-_]/g,function(b){return b.charAt(1).toUpperCase()})};baidu.browser=baidu.browser||{};if(/msie (\d+\.\d)/i.test(navigator.userAgent))baidu.browser.ie=baidu.ie=document.documentMode||+RegExp.$1;
baidu.dom.getStyle=function(a,b){var f=baidu.dom;a=f.g(a);b=baidu.string.toCamelCase(b);var e=a.style[b];if(!e){var d=f._styleFixer[b];e=a.currentStyle||(baidu.browser.ie?a.style:getComputedStyle(a,null));e=d&&d.get?d.get(a,e):e[d||b]}if(d=f._styleFilter)e=d.filter(b,e,"get");return e};baidu.getStyle=baidu.dom.getStyle;if(/opera\/(\d+\.\d)/i.test(navigator.userAgent))baidu.browser.opera=+RegExp.$1;baidu.browser.isWebkit=/webkit/i.test(navigator.userAgent);
baidu.browser.isGecko=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);baidu.browser.isStrict=document.compatMode=="CSS1Compat";
baidu.dom.getPosition=function(a){a=baidu.dom.g(a);var b=baidu.dom.getDocument(a),f=baidu.browser,e=baidu.dom.getStyle;f.isGecko>0&&b.getBoxObjectFor&&e(a,"position");var d={left:0,top:0},c;if(a==(f.ie&&!f.isStrict?b.body:b.documentElement))return d;if(a.getBoundingClientRect){a=a.getBoundingClientRect();d.left=Math.floor(a.left)+Math.max(b.documentElement.scrollLeft,b.body.scrollLeft);d.top=Math.floor(a.top)+Math.max(b.documentElement.scrollTop,b.body.scrollTop);d.left-=b.documentElement.clientLeft;
d.top-=b.documentElement.clientTop;a=b.body;b=parseInt(e(a,"borderLeftWidth"));e=parseInt(e(a,"borderTopWidth"));if(f.ie&&!f.isStrict){d.left-=isNaN(b)?2:b;d.top-=isNaN(e)?2:e}}else{c=a;do{d.left+=c.offsetLeft;d.top+=c.offsetTop;if(f.isWebkit>0&&e(c,"position")=="fixed"){d.left+=b.body.scrollLeft;d.top+=b.body.scrollTop;break}c=c.offsetParent}while(c&&c!=a);if(f.opera>0||f.isWebkit>0&&e(a,"position")=="absolute")d.top-=b.body.offsetTop;for(c=a.offsetParent;c&&c!=b.body;){d.left-=c.scrollLeft;if(!f.opera||
c.tagName!="TR")d.top-=c.scrollTop;c=c.offsetParent}}return d};(function(){var a=navigator.userAgent;if(/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(a)&&!/chrome/i.test(a))baidu.browser.safari=+(RegExp.$1||RegExp.$2)})();
baidu.dom.ready=function(){function a(){if(!f){f=true;for(var c=0,g=d.length;c<g;c++)d[c]()}}function b(){if(!e){e=true;var c=document,g=window,i=baidu.browser.opera;if(c.addEventListener)c.addEventListener("DOMContentLoaded",i?function(){if(!f){for(var h=0;h<c.styleSheets.length;h++)if(c.styleSheets[h].disabled){setTimeout(arguments.callee,0);return}a()}}:a,false);else if(baidu.browser.ie&&g==top)(function(){if(!f){try{c.documentElement.doScroll("left")}catch(h){setTimeout(arguments.callee,0);return}a()}})();
else if(baidu.browser.safari){var j;(function(){if(!f)if(c.readyState!="loaded"&&c.readyState!="complete")setTimeout(arguments.callee,0);else{if(j===undefined){j=0;var h=c.getElementsByTagName("style"),k=c.getElementsByTagName("link");if(h)j+=h.length;if(k){h=0;for(var l=k.length;h<l;h++)k[h].getAttribute("rel")=="stylesheet"&&j++}}c.styleSheets.length!=j?setTimeout(arguments.callee,0):a()}})()}g.attachEvent?g.attachEvent("onload",a):g.addEventListener("load",a,false)}}var f=false,e=false,d=[];return function(c){b();
f?c():d[d.length]=c}}();(function(){var a=RegExp("(^[\\s\\t\\xa0\\u3000]+)|([\\u3000\\xa0\\s\\t]+$)","g");baidu.string.trim=function(b){return String(b).replace(a,"")}})();baidu.trim=baidu.string.trim;baidu.dom.hasClass=function(a,b){a=baidu.dom.g(a);var f=baidu.string.trim(b).split(/\s+/),e=f.length;for(b=a.className.split(/\s+/).join(" ");e--;)if(!RegExp("(^| )"+f[e]+"( |$)").test(b))return false;return true};baidu.event=baidu.event||{};baidu.event._listeners=baidu.event._listeners||[];
baidu.lang=baidu.lang||{};baidu.lang.isString=function(a){return"[object String]"==Object.prototype.toString.call(a)};baidu.isString=baidu.lang.isString;baidu.dom._g=function(a){if(baidu.lang.isString(a))return document.getElementById(a);return a};baidu._g=baidu.dom._g;
baidu.event.on=function(a,b,f){b=b.replace(/^on/i,"");a=baidu.dom._g(a);var e=function(i){f.call(a,i)},d=baidu.event._listeners,c=baidu.event._eventFilter,g=b;b=b.toLowerCase();if(c&&c[b]){e=c[b](a,b,e);g=e.type;e=e.listener}if(a.addEventListener)a.addEventListener(g,e,false);else a.attachEvent&&a.attachEvent("on"+g,e);d[d.length]=[a,b,f,e,g];return a};baidu.on=baidu.event.on;
baidu.event.un=function(a,b,f){a=baidu.dom._g(a);b=b.replace(/^on/i,"").toLowerCase();for(var e=baidu.event._listeners,d=e.length,c=!f,g,i;d--;){g=e[d];if(g[1]===b&&g[0]===a&&(c||g[2]===f)){i=g[4];g=g[3];if(a.removeEventListener)a.removeEventListener(i,g,false);else a.detachEvent&&a.detachEvent("on"+i,g);e.splice(d,1)}}return a};baidu.un=baidu.event.un;baidu.lang.isFunction=function(a){return"[object Function]"==Object.prototype.toString.call(a)};
baidu.page.lazyLoadImage=function(a){a=a||{};a.preloadHeight=a.preloadHeight||0;baidu.dom.ready(function(){var b=document.getElementsByTagName("IMG"),f=b,e=b.length,d=0,c=baidu.page.getScrollTop()+baidu.page.getViewHeight()+a.preloadHeight,g;if(a.className)for(f=[];d<e;++d)baidu.dom.hasClass(b[d],a.className)&&f.push(b[d]);d=0;for(e=f.length;d<e;++d){g=f[d];if(baidu.dom.getPosition(g).top<c)g.src=g.getAttribute("data-tangram-ori-src")}var i=function(){for(var j=baidu.page.getScrollTop()+baidu.page.getViewHeight()+
a.preloadHeight,h,k=true,l=0,m=f.length;l<m;++l){g=f[l];(h=g.getAttribute("data-tangram-ori-src"))&&(k=false);if(baidu.dom.getPosition(g).top<j&&h){g.src=h;g.removeAttribute("data-tangram-ori-src");baidu.lang.isFunction(a.onlazyload)&&a.onlazyload(g)}}k&&baidu.un(window,"scroll",i)};baidu.on(window,"scroll",i)})};